# Generated by Django 5.2.8 on 2025-11-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_text', models.TextField()),
                ('contact_type', models.CharField(max_length=32)),
                ('contact_value', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NegativeFeedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_text', models.TextField()),
                ('reason', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
